#!/usr/bin/env python3
"""run.py - the mme regression suite.

    python run.py                 run every scenario, compare with the goldens
    python run.py --update        re-bless: write what came out as the golden
    python run.py -k explorer     only the scenarios whose name has "explorer"
    python run.py --repeat 3      run everything N times and fail on any drift
    python run.py --list          print the scenarios and what each one guards
    python run.py --build         rebuild bin/ and pbin/ from tree/ and ptree/
    python run.py --jobs 8        how many scenarios run at once (default: 8)

Each scenario drives a real mme.exe inside a ConPTY with hx.exe (../harness.c
with background and attribute dumps added) and compares what came out with
golden/<name>.txt.
Every run gets its own copy of the exe with its own empty mme-data, so the
suite never sees the user's settings and two scenarios never collide.

See README.md for how to add one.
"""
from __future__ import print_function

import argparse
import difflib
import io
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor

# the screens carry Nerd Font glyphs; stdout here is cp1252, which raises on
# them and would kill a run at the very moment it has something to report
for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

HERE = os.path.dirname(os.path.abspath(__file__))
EDITOR = os.path.dirname(HERE)              # the checkout this suite tests

# The fixtures and the scenarios' work folders must not sit inside a git
# repository, or every scenario sees the editor's own; they are generated, so
# they live in a build directory outside the checkout.
BUILD = os.environ.get("MME_TEST_WORK") or os.path.join(tempfile.gettempdir(), "mme-test")

HARNESS = os.path.join(HERE, "hx.exe")   # ../harness.c plus the b: and a: steps
TREE = os.path.join(HERE, "tree")           # a copy of the editor sources
PTREE = os.path.join(HERE, "ptree")         # the same, plus the tick profiler
BIN = os.path.join(HERE, "bin", "mme.exe")
BROWSER = os.path.join(HERE, "browser")   # the no-op rundll32, ahead of System32
PBIN = os.path.join(HERE, "pbin", "mme.exe")
FIX = os.path.join(BUILD, "fix")            # generated by mkfix.py
GOLDEN = os.path.join(HERE, "golden")
WORK = os.path.join(BUILD, "work")          # one folder per scenario
SEED = os.path.join(HERE, "settings.seed.json")
PERF_BASELINE = os.path.join(GOLDEN, "perf-baseline.json")

# a tick longer than this many microseconds is what the profiler records
TICK_MS = 20


# ------------------------------------------------------------------ scenarios

def stub_cmd(*args):
    """stublsp.py as a settings.json command, for a scenario that needs two of
    them with different arguments (stub_lsp= gives every language the same one)"""
    return " ".join(["python", os.path.join(HERE, "stublsp.py").replace("\\", "/")] +
                    list(args))


class Scen(object):
    """One scenario: what to open, what to press, and what it guards."""

    def __init__(self, name, target, steps, guards, settings=None, subs=None,
                 perf=False, private=False, stub_lsp=(), watch=(),
                 inline_lsp=None, fake_browser=False, stub_claude=None):
        self.stub_lsp = stub_lsp    # languages that get reg/stublsp.py
        self.inline_lsp = inline_lsp  # stublsp.py as mme.inlineCompletionServer,
                                    # with this --auth= state ("out", "in",
                                    # "error", "busy")
        self.fake_browser = fake_browser  # reg/browser goes in front of the PATH,
                                    # so opening a URL runs the no-op rundll32
                                    # there and never a real browser window
        self.stub_claude = stub_claude  # stubclaude.py as the Messages API, with
                                    # this --mode= ("ok", "401", "529",
                                    # "refusal"); mme.chat.baseUrl points at it
                                    # and mme.chat.apiKey is its dummy key
        self.name = name
        self.target = target        # relative to fix/, or an absolute path
        self.steps = steps          # harness steps
        self.guards = guards        # one line: what a failure here means
        self.settings = settings or {}   # settings.json values over the seed
        self.subs = subs or []      # extra (regex, replacement) masks
        self.perf = perf            # also assert on the event-loop tick profile
        self.private = private      # give the scenario its own copy of target
        self.watch = watch          # names under the scenario's own target folder
                                    # whose bytes are reported after the run; needs
                                    # private=True, or there is nothing mme may write to


# keys that go in as raw CSI u (the kitty protocol): "<code>;<mods>u",
# mods = 1 + 1*shift + 2*alt + 4*ctrl
def csiu(ch, ctrl=False, shift=False, alt=False):
    mods = 1 + (1 if shift else 0) + (2 if alt else 0) + (4 if ctrl else 0)
    return "`[%d;%du" % (ord(ch), mods)


CTRL_SHIFT_P = csiu("p", ctrl=True, shift=True)     # Command Palette
CTRL_P = csiu("p", ctrl=True)                       # Go to File
CTRL_F = csiu("f", ctrl=True)                       # Find
CTRL_H = csiu("h", ctrl=True)                       # Replace
CTRL_SHIFT_F = csiu("f", ctrl=True, shift=True)     # Find in Files
CTRL_SHIFT_H = csiu("h", ctrl=True, shift=True)     # Replace in Files
CTRL_SHIFT_G = csiu("g", ctrl=True, shift=True)     # Source Control
CTRL_SHIFT_E = csiu("e", ctrl=True, shift=True)     # Explorer
CTRL_SHIFT_M = csiu("m", ctrl=True, shift=True)     # Problems
CTRL_SHIFT_U = csiu("u", ctrl=True, shift=True)     # Output
CTRL_SHIFT_V = csiu("v", ctrl=True, shift=True)     # Markdown preview
CTRL_COMMA = csiu(",", ctrl=True)                   # Settings
CTRL_BACKTICK = csiu("`", ctrl=True)                # Terminal panel
CTRL_K = csiu("k", ctrl=True)
CTRL_S = csiu("s", ctrl=True)
CTRL_D = csiu("d", ctrl=True)
CTRL_W = csiu("w", ctrl=True)
CTRL_Z = csiu("z", ctrl=True)
CTRL_Y = csiu("y", ctrl=True)
CTRL_C = csiu("c", ctrl=True)
CTRL_V = csiu("v", ctrl=True)
CTRL_A = csiu("a", ctrl=True)
CTRL_B = csiu("b", ctrl=True)
CTRL_0 = csiu("0", ctrl=True)
CTRL_J = csiu("j", ctrl=True)
ALT_Z = csiu("z", alt=True)
ALT_R = csiu("r", alt=True)                         # Find: use regular expression
ALT_P = csiu("p", alt=True)                         # Replace: Preserve Case (AB)
CTRL_ALT_ENTER = "`[13;7u"                          # Replace All
ALT_SHIFT_I = csiu("i", shift=True, alt=True)       # Add Cursors to Line Ends
CTRL_ALT_I = csiu("i", ctrl=True, alt=True)         # Chat: Open Chat
CTRL_I = csiu("i", ctrl=True)                       # Inline Chat: Start
CTRL_ENTER = "`[13;5u"                              # Inline Chat: Accept Changes
ENTER = "|"
ESC = "`"
UP, DOWN, RIGHT, LEFT = "`[A", "`[B", "`[C", "`[D"
HOME, END = "`[H", "`[F"
PGUP, PGDN = "`[5~", "`[6~"
SH_DOWN, SH_RIGHT = "`[1;2B", "`[1;2C"
# a bare 0x09 does not survive ConPTY's input translation: Tab goes in as CSI u
TAB = "`[9;1u"
SHIFT_TAB = "`[Z"
CTRL_HOME, CTRL_END = "`[1;5H", "`[1;5F"
BKSP = "\x7f"


def click(col, row):
    """an SGR mouse press and release at 1-based column/row"""
    return ["k:`[<0;%d;%dM" % (col, row), "k:`[<0;%d;%dm" % (col, row)]


def crows(*rows):
    """text-colour dumps of those screen rows (0 based: 0 menu, 29 status bar)"""
    return ["c:%d" % r for r in rows]


def brows(*rows):
    """background-colour dumps: the selection, the find matches, the diff"""
    return ["b:%d" % r for r in rows]


def arows(*rows):
    """attribute dumps: bold, italic, the curly underline of a diagnostic"""
    return ["a:%d" % r for r in rows]


# the editor's text starts at screen row 3 (0 menu, 1 tabs, 2 breadcrumbs)
COLOUR_ROWS = crows(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

# Search Editor: New Search Editor from the palette; the query box then has the keys
SE_NEW = ["w:1500", "k:" + CTRL_SHIFT_P, "w:400", "k:New Search Editor", "w:500", "k:|", "w:600"]
CTRL_O = csiu("o", ctrl=True)
CTRL_PGUP = "`[5;5~"
F12 = "`[24~"

SCENARIOS = [
    # ---------------------------------------------------------- plain editing
    Scen("edit-type-undo-redo", "lang/edit.c",
         ["w:900", "k:" + DOWN * 3, "k:" + END, "k:| /* typed here */", "w:400", "d",
          "k:" + CTRL_Z, "w:400", "d", "k:" + CTRL_Y, "w:400", "d"],
         "typing, the dirty dot, undo and redo, and the re-highlight after each"),
    Scen("edit-select-copy-paste", "lang/edit.c",
         ["w:900", "k:" + DOWN * 12, "k:" + HOME, "k:" + SH_DOWN * 2, "w:300", "d",
          "k:" + CTRL_C, "k:" + CTRL_END, "k:" + CTRL_V, "w:500", "d"],
         "Shift selection, the selection colours, Ctrl+C and Ctrl+V"),
    Scen("edit-selection-colours", "lang/edit.c",
         ["w:900", "k:" + DOWN * 12, "k:" + HOME, "k:" + SH_DOWN * 2, "k:" + SH_RIGHT * 6,
          "w:400"] + brows(14, 15, 16, 17) + crows(15, 16),
         "the background of a selection and of the cursor's own line"),
    Scen("edit-navigation", "mini/big.c",
         ["w:1000", "k:" + PGDN * 3, "w:300", "d", "k:" + END, "w:200", "d",
          "k:" + CTRL_END, "w:400", "d", "k:" + CTRL_HOME, "w:300", "d"],
         "PgDn, End, Ctrl+End / Ctrl+Home and the scrolling that follows them"),
    Scen("edit-snippet-absorbs", "lang/edit.c",
         # the suite turns timed suggestions off, so ask for the list
         ["w:1200", "k:`[1;5F", "k:|", "w:400", "k:int main", "w:600",
          "k:`[32;5u", "w:1500", "k:	", "w:1200", "d"],
         "a snippet whose body repeats what was already typed must not say it "
         "twice. Typing \"int main\" and taking the main snippet gave \"int int "
         "main (...)\": only the snippet's prefix was absorbed, never its body",
         private=True),
    Scen("edit-multi-cursor", "lang/edit.c",
         ["w:900", "k:" + DOWN * 12, "k:" + HOME, "k:" + CTRL_D, "w:200",
          "k:" + CTRL_D, "w:200", "k:" + CTRL_D, "w:300", "d",
          "k:XX", "w:400", "d"],
         "Ctrl+D adding a cursor per match, and typing into every cursor at once"),
    Scen("edit-multi-cursor-alt-click", "lang/edit.c",
         ["w:900"] + click(20, 6) + ["w:200"] + ["k:`[<8;20;8M", "k:`[<8;20;8m"] +
         ["w:200", "k:`[<8;20;10M", "k:`[<8;20;10m", "w:400", "d", "k:Q", "w:400", "d"],
         "Alt+Click putting extra cursors where they were clicked"),

    # ------------------------------------------------------- syntax colouring
    Scen("colour-c", "lang/edit.c", ["w:2500"] + COLOUR_ROWS,
         "the C highlighter: keywords, types, strings, numbers, comments"),
    Scen("colour-go", "lang/demo.go", ["w:2500"] + COLOUR_ROWS,
         "the Go highlighter"),
    Scen("colour-tsx", "lang/card.tsx", ["w:2500"] + COLOUR_ROWS,
         "the TSX highlighter: JSX tags, types, template strings"),
    Scen("colour-js", "lang/app.js", ["w:2500"] + COLOUR_ROWS,
         "the JavaScript highlighter"),
    Scen("colour-css", "lang/site.css", ["w:2500"] + COLOUR_ROWS,
         "the CSS highlighter: selectors, properties, colours, at-rules"),
    Scen("colour-md", "lang/doc.md", ["w:2500"] + COLOUR_ROWS,
         "the Markdown highlighter: headings, emphasis, lists, fenced code"),
    Scen("colour-json", "lang/conf.json", ["w:2500"] + COLOUR_ROWS,
         "the JSON highlighter: keys, strings, numbers, true/false/null"),
    Scen("colour-python", "lang/util.py", ["w:2500"] + COLOUR_ROWS,
         "the Python highlighter: docstrings, f-strings, decorators, keywords"),
    Scen("colour-bracket-pairs", "lang/app.js",
         ["w:2500", "k:" + DOWN * 20, "w:600"] + COLOUR_ROWS,
         "editor.bracketPairColorization: nested brackets by depth"),

    # ------------------------------------------------- highlight invalidation
    Scen("hl-invalidate-block-comment", "lang/app.js",
         ["w:2500"] + COLOUR_ROWS +
         ["k:" + CTRL_HOME, "k:/*", "w:900"] + COLOUR_ROWS +
         ["k:" + CTRL_Z, "w:700"] + COLOUR_ROWS +
         ["k:" + CTRL_Y, "w:700"] + COLOUR_ROWS,
         "inserting /* recolours every line below it, and undo puts the colours back exactly"),
    Scen("hl-invalidate-template-string", "lang/app.js",
         ["w:2500", "k:" + CTRL_HOME, "k:" + DOWN * 2, "k:" + END, "w:600"] + COLOUR_ROWS +
         ["k:" + csiu("`"), "w:700"] + COLOUR_ROWS +
         ["k:" + CTRL_Z, "w:700"] + COLOUR_ROWS,
         "one backtick turns the rest of the file into a template string, and undo "
         "puts every colour back exactly (the third block must equal the first)",
         settings={"editor.autoClosingBrackets": "never"}),

    # ------------------------------------------------------- minified / long lines
    Scen("mini-md5", "mini/md5.js",
         ["w:1500", "d", "k:" + DOWN, "k:" + END, "w:600", "d"] + crows(3, 4, 5, 6),
         "a 12.7 KB single line (md5.js): it draws and End walks to its end",
         perf=True),
    Scen("mini-mid", "mini/mid.js",
         ["w:1500", "d", "k:" + DOWN, "k:" + END, "w:600", "d",
          "k:" + PGDN, "w:400", "d"] + crows(3, 4),
         "a ~12 KB line, the window the old tokenizer hang lived in",
         perf=True),
    Scen("mini-boot-css", "mini/boot.min.css",
         ["w:1500", "d", "k:" + END, "w:800", "d", "k:" + CTRL_END, "w:800", "d"],
         "boot.min.css: a 190 KB line, past editor.maxTokenizationLineLength",
         perf=True),
    Scen("mini-found-js", "mini/found.min.js",
         ["w:2000", "d", "k:" + END, "w:1000", "d"],
         "found.min.js: 531 KB on one line, the worst case for the line renderer",
         perf=True),
    Scen("mini-big-c", "mini/big.c",
         ["w:1200", "k:" + PGDN * 6, "w:500", "d", "k:" + CTRL_END, "w:600", "d"],
         "a 1400 line C file scrolled: the incremental tokenizer keeps up",
         perf=True),

    # ------------------------------------------------------------- the explorer
    Scen("explorer-tree", "proj", ["w:1800", "d"],
         "the Explorer's first screen: compact folders, sort order, OPEN EDITORS, TIMELINE"),
    Scen("explorer-click-file", "proj",
         ["w:1800"] + click(12, 11) + ["w:900", "d"],
         "a click in the Explorer opens the file in a tab"),
    Scen("explorer-expand-folder", "proj",
         ["w:1800"] + click(10, 9) + ["w:700", "d"] + click(10, 7) + ["w:700", "d"],
         "clicking a folder expands it and its children appear indented"),
    Scen("explorer-scroll", "proj",
         ["w:1800"] + click(10, 8) + ["w:900", "d",
                                      "k:`[<65;10;15M", "k:`[<65;10;15M", "k:`[<65;10;15M", "w:600", "d"],
         "a long tree scrolls with the wheel and shows its scrollbar"),
    Scen("explorer-open-editors", "proj",
         ["w:1800"] + click(12, 11) + ["w:700"] + click(12, 13) + ["w:700"] +
         click(10, 3) + ["w:700", "d"],
         "OPEN EDITORS lists the open tabs and expands"),

    # ------------------------------------------------------------------- tabs
    Scen("tabs-open-switch-close", "proj",
         ["w:1800"] + click(12, 11) + ["w:600"] + click(12, 13) + ["w:600"] +
         click(12, 14) + ["w:800", "d"] +
         click(40, 2) + ["w:600", "d", "k:" + CTRL_W, "w:600", "d"],
         "three tabs open, a click on the first tab switches to it, Ctrl+W closes it"),
    Scen("tabs-preview", "proj",
         ["w:1800"] + click(12, 11) + ["w:600", "d"] + click(12, 13) + ["w:800", "d"] +
         arows(1),
         "workbench.editor.enablePreview: one preview tab, replaced rather than added",
         settings={"workbench.editor.enablePreview": True}),
    Scen("tabs-preview-italic", "proj",
         # main.c is clicked, then clicked again in the text (a click in the
         # Explorer leaves the keys there) and edited, so it stops being the
         # preview tab. readme.md then opens as the preview tab, and clicking
         # back to main.c leaves it in the bar but not in front, which is the
         # only time a preview tab is drawn in italics.
         ["w:1800"] + click(12, 11) + ["w:600"] + click(60, 6) +
         ["w:400", "k:X", "w:400"] + click(12, 13) +
         ["w:800"] + click(40, 2) + ["w:800", "d"] + arows(1) + crows(1),
         "a preview tab that is not in front is drawn in italics (S_TAB_PREVIEW)",
         settings={"workbench.editor.enablePreview": True}),
    Scen("tabs-pin", "proj",
         ["w:1800"] + click(12, 11) + ["w:600"] +
         ["k:" + CTRL_K, "k:`[13;2u", "w:700", "d"] +
         click(12, 13) + ["w:800", "d"],
         "Ctrl+K Shift+Enter pins a tab and a pinned tab keeps its place"),

    # -------------------------------------- palette, go to file, find, search
    Scen("palette-open", "lang/edit.c",
         ["w:900", "k:" + CTRL_SHIFT_P, "w:600", "d"],
         "the command palette opens on the recently used commands"),
    Scen("palette-filter", "lang/edit.c",
         ["w:900", "k:" + CTRL_SHIFT_P, "w:300", "k:fold", "w:700", "d"],
         "typing filters the palette and highlights what matched"),
    Scen("gotofile", "proj",
         ["w:1800", "k:" + CTRL_P, "w:700", "d", "k:beta", "w:800", "d"],
         "Go to File lists the folder's files and filters them"),
    Scen("gotofile-symbol", "lang/edit.c",
         ["w:900", "k:" + CTRL_P, "w:400", "k:@", "w:800", "d"],
         "@ in Go to File switches it to the file's symbols"),
    Scen("find-in-file", "lang/edit.c",
         ["w:900", "k:" + CTRL_F, "w:300", "k:total", "w:700", "d",
          "k:|", "w:400", "d"],
         "Ctrl+F: the box, the match count, every match lit, Enter goes to the next"),
    Scen("find-match-colours", "lang/edit.c",
         ["w:900", "k:" + CTRL_F, "w:300", "k:total", "w:900"] + brows(15, 16, 19, 20),
         "the background of the match in front and of the other matches"),
    Scen("replace-in-file", "lang/edit.c",
         ["w:900", "k:" + CTRL_H, "w:300", "k:total", "k:`[Z", "w:200",
          "k:SUM", "w:700", "d"],
         "Ctrl+H opens the replace box under Find with both fields filled"),
    Scen("search-in-folder", "proj",
         ["w:1800", "k:" + CTRL_SHIFT_F, "w:400", "k:NeedleWord", "w:3500", "d"],
         "Find in Files: the worker's result count and the grouped hits"),
    Scen("replace-in-folder", "proj",
         ["w:1800", "k:" + CTRL_SHIFT_H, "w:400", "k:NeedleWord", "w:3000",
          "k:" + TAB, "w:300", "k:HayStack", "w:2500", "d"],
         "Replace in Files shows the replacement struck through beside each hit"),
    Scen("replace-preserve-case", "case/case.txt",
         ["w:900", "k:" + CTRL_H, "w:300", "k:foo", "k:" + TAB, "w:200", "k:baz",
          "k:" + ALT_P, "w:500", "d", "b:4", "k:" + CTRL_ALT_ENTER, "w:700", "d"],
         "AB (Alt+P) in the replace box lights up, and Replace All gives each match\n"
         "         its own case: baz, Baz, BAZ, and baz for fOO (its first letter's)"),
    Scen("replace-preserve-case-hyphen", "case/case.txt",
         ["w:900", "k:" + CTRL_H, "w:300", "k:foo-bar", "k:" + TAB, "w:200", "k:new-name",
          "k:" + ALT_P, "k:" + CTRL_ALT_ENTER, "w:700", "d"],
         "Preserve Case part by part, like VS Code: Foo-Bar gives New-Name, each\n"
         "         part between the '-' in its own part's case"),
    Scen("replace-preserve-case-underscore", "case/case.txt",
         ["w:900", "k:" + CTRL_H, "w:300", "k:foo_bar", "k:" + TAB, "w:200", "k:new_name",
          "k:" + ALT_P, "k:" + CTRL_ALT_ENTER, "w:700", "d"],
         "Preserve Case part by part: Foo_Bar gives New_Name, FOO_BAR NEW_NAME"),
    Scen("replace-preserve-case-search", "case",
         ["w:1800", "k:" + CTRL_SHIFT_H, "w:400", "k:foo", "w:3000",
          "k:" + TAB, "w:300", "k:baz", "k:" + ALT_P, "w:1500", "d", "b:3",
          "k:" + CTRL_ALT_ENTER, "w:800", "d", "k:" + ENTER, "w:1500", "d"],
         "the Search view's AB: the preview shows each hit's replacement in its\n"
         "         case, and Replace All writes them so",
         private=True, watch=("case/case.txt",)),

    # ------------------------------------------------------------ editorconfig
    Scen("editorconfig-indent", "ec/proj/four.c",
         ["w:1200", "d", "k:" + DOWN, "k:" + HOME, "k:" + TAB, "w:400", "d"],
         ".editorconfig's indent_style / indent_size win over the detected indent:\n"
         "         a file indented by 4 shows Spaces: 2, and Tab puts in 2 spaces"),
    Scen("editorconfig-tabs", "ec/proj/main.go",
         ["w:1200", "d"],
         "[*.{go,mk}] indent_style = tab, tab_width = 8: Tab Size: 8, a tab is 8 wide"),
    Scen("editorconfig-closer-wins", "ec/proj/sub/deep.c",
         ["w:1200", "d"],
         "the .editorconfig closest to the file says the last word: Spaces: 4\n"
         "         from sub/ over the root's 2, and over the detected 2"),
    Scen("editorconfig-glob-star", "ec/proj/lib/a/b/deep.js",
         ["w:1200", "d"],
         "[lib/**.js] reaches a file folders below lib/: Spaces: 3"),
    Scen("editorconfig-glob-range", "ec/proj/num2.txt",
         ["w:1200", "d"],
         "[num{1..3}.txt] takes num2.txt: Spaces: 6"),
    Scen("editorconfig-glob-range-out", "ec/proj/num4.txt",
         ["w:1200", "d"],
         "[num{1..3}.txt] does not take num4.txt: [*]'s Spaces: 2"),
    Scen("editorconfig-not-root", "ec/open/a.txt",
         ["w:1200", "d"],
         "a .editorconfig without root = true lets the one above it speak too:\n"
         "         indent_style = tab here, indent_size = 7 from above: Tab Size: 7"),
    Scen("editorconfig-charset", "ec/proj/cafe.latin",
         ["w:1200", "d"],
         "charset = latin1 reads the file as Latin-1: cafe with its accent, and\n"
         "         Western (ISO 8859-1) in the status bar"),
    Scen("editorconfig-new-file", "ec/proj/brand-new.txt",
         ["w:1200", "d"],
         "a file that is not there yet gets end_of_line = crlf at once: CRLF"),
    Scen("editorconfig-save", "ec/proj",
         ["w:1800", "k:" + CTRL_P, "w:500", "k:save.txt", "w:500", "k:|", "w:800",
          "k:x", "k:" + CTRL_S, "w:900", "d"],
         "saving does what .editorconfig says: the trailing blanks go, a final\n"
         "         newline comes, and every line ends in CR LF",
         private=True, watch=("proj/save.txt",)),

    # ---------------------------------------------------------- search editor
    Scen("search-editor-new", "sedit",
         SE_NEW + ["k:total", "w:2000", "d"] + crows(4, 6, 7, 12) + brows(8, 13),
         "Search Editor: New Search Editor opens a 'Search: total' tab whose results are VS Code's "
         ".code-search text: the count, each path, '  3: ' matches and '  2  ' context lines, "
         "an empty line at a gap; paths, line numbers and matches coloured"),
    Scen("search-editor-open-result", "sedit",
         SE_NEW + ["k:total", "w:2000", "k:" + TAB, "k:" + TAB] + ["k:" + DOWN] * 13 +
         ["w:300", "d", "k:|", "w:1200", "d", "k:" + CTRL_PGUP, "w:500"] + ["k:" + UP] * 9 +
         ["k:" + F12, "w:1200", "d"],
         "Enter or F12 on a result line opens its file at that line with the match selected"),
    Scen("search-editor-select-copy", "sedit",
         SE_NEW + ["k:total", "w:2000", "k:" + TAB, "k:" + TAB] + ["k:" + DOWN] * 6 +
         ["k:" + SH_DOWN, "k:" + SH_DOWN, "w:300"] + brows(10, 11, 12) +
         ["k:" + CTRL_C, "k:" + csiu("n", ctrl=True), "w:500", "k:" + CTRL_V, "w:600", "d"],
         "the results are text that Shift+arrows select (the selection's background) and "
         "Ctrl+C copies: pasted into a new file they come out as they are"),
    Scen("search-editor-rerun", "sedit",
         SE_NEW + ["k:total", "w:1200", "d", "k:" + csiu("r", ctrl=True, shift=True), "w:1500", "d",
                   "k:" + csiu("c", alt=True), "k:" + csiu("l", alt=True), "k:|", "w:1500", "d"],
         "with search.searchOnType off nothing is searched until Ctrl+Shift+R (Rerun Search); "
         "Alt+C (Match Case) and Alt+L (context lines off) then Enter search again",
         settings={"search.searchOnType": False}),
    Scen("search-editor-save", "sedit",
         SE_NEW + ["k:total", "w:2000", "k:" + CTRL_S, "w:600", "k:|", "w:800", "k:" + CTRL_W, "w:500",
                   "k:" + CTRL_O, "w:600", "d", "k:total.code-search", "w:800", "k:|", "w:1200", "d"],
         "Ctrl+S writes VS Code's header and results to <query>.code-search, and that file "
         "opens again as a Search Editor with its query and results",
         private=True, watch=("sedit/total.code-search",)),
    Scen("search-editor-open-file", "sedit/saved.code-search",
         ["w:1800", "d"] + crows(7, 8) + brows(2),
         "a .code-search file opens in the Search Editor: its header fills the query, "
         "Match Case and the context lines, and its results show as they were saved"),
    Scen("search-editor-from-view", "sedit",
         ["w:1500", "k:" + CTRL_SHIFT_F, "w:400", "k:total", "w:2000", "d",
          "k:" + csiu("\r", alt=True), "w:2000", "d"],
         "the Search view says 'Open in editor' under its count, and Alt+Enter opens its "
         "search in a Search Editor with the context lines"),

    # -------------------------------------------------------------------- git
    Scen("git-gutter-and-blame", "gitrepo/tracked.c",
         ["w:2500", "d"] + crows(3, 14, 17, 18),
         "the gutter's added / changed / deleted bars and the blame decoration"),
    Scen("git-scm-view", "gitrepo",
         ["w:2500", "k:" + CTRL_SHIFT_G, "w:1500", "d"],
         "SOURCE CONTROL: the branch, Changes with M / U letters, and the commit GRAPH"),
    Scen("git-diff-view", "gitrepo",
         ["w:2500", "k:" + CTRL_SHIFT_G, "w:1500"] + click(13, 6) + ["w:1800", "d"],
         "the side by side diff editor of a working-tree change"),
    Scen("git-diff-colours", "gitrepo",
         ["w:2500", "k:" + CTRL_SHIFT_G, "w:1500"] + click(13, 6) + ["w:1800"] +
         brows(16, 17, 19, 20) + crows(16, 19),
         "the added and removed backgrounds of the diff editor"),
    Scen("git-diff-word-wrap", "gitrepo",
         ["w:2500", "k:" + CTRL_SHIFT_G, "w:1500"] + click(13, 6) + ["w:1800", "k:" + ALT_Z, "w:800", "d"],
         "Alt+Z wraps the diff's long lines too: a line wider than its side goes on\n"
         "         in the rows under it, the other side's rows stay level with it, and\n"
         "         the horizontal scrollbar goes away"),
    Scen("git-file-history", "gitrepo/tracked.c",
         ["w:2500", "k:" + CTRL_SHIFT_P, "w:300", "k:View File History", "w:700",
          "k:|", "w:2000", "d"],
         "Git: View File History lists the commits that touched the file"),
    Scen("git-diff-leading-dashes", "dashrepo",
         ["w:2500", "k:" + CTRL_SHIFT_G, "w:1500"] + click(13, 6) + ["w:1800", "d"],
         "a deleted line that starts \"--\" stays in the diff: mistaking it for the\n"
         "         diff's own \"---\" header drops it and shifts every old line number,\n"
         "         and Revert Selected Ranges then writes the file back without it"),
    Scen("git-diff-word-changed", "wordrepo",
         ["w:2500", "k:" + CTRL_SHIFT_G, "w:1500"] + click(13, 6) + ["w:1800", "d"] +
         brows(3, 4, 5, 6),
         "only the word that changed is brighter than the rest of its line: the\n"
         "         changed line is paired with the line it became and not with the\n"
         "         line inserted above it, which would paint both of them whole"),
    Scen("theme-token-customizations", "lang/edit.c",
         ["w:2000"] + crows(3, 5, 7, 9),
         "editor.tokenColorCustomizations recolours the code over the theme, by "
         "named group and by textMateRules, and a block named for the current theme "
         "wins. It must reach the grammar's own colours and not only the fallback "
         "highlighter, or it does nothing in the default setup",
         settings={"workbench.colorTheme": "Dark+",
                   "editor.tokenColorCustomizations": {
                       "comments": "#111111",
                       "[Dark+]": {"comments": "#FF8800", "numbers": "#00FFAA"},
                       "[Not This One]": {"comments": "#00FF00"},
                       "textMateRules": [{"scope": "string",
                                          "settings": {"foreground": "#4444FF"}}]}}),
    Scen("theme-color-customizations", "wordrepo",
         ["w:2500", "k:" + CTRL_SHIFT_G, "w:1500"] + click(13, 6) + ["w:1800"] + brows(4, 5),
         "workbench.colorCustomizations puts a colour over the theme, and a block\n"
         "         named for the current theme wins over a plain key. Without it the only\n"
         "         way to change one colour is to edit or swap the whole theme",
         settings={"workbench.colorTheme": "Dark+",
                   "workbench.colorCustomizations": {
                       "diffEditor.removedTextBackground": "#111111",
                       "[Dark+]": {"diffEditor.removedTextBackground": "#FF8800"},
                       "[Not This Theme]": {"diffEditor.removedTextBackground": "#00FF00"}}}),
    Scen("git-blame-toggle", "gitrepo/tracked.c",
         ["w:2500", "k:" + CTRL_SHIFT_P, "w:300", "k:Toggle Git Blame", "w:700",
          "k:|", "w:1200", "d"],
         "the blame decoration can be switched off"),

    Scen("perf-find-long-line", "mini/one400k.txt",
         ["w:2000", "k:" + CTRL_F, "w:800", "k:f", "w:1200", "k:o", "w:1200",
          "k:x", "w:2500", "d"],
         "typing into the Find box on one 400 KB line. The word-occurrence overlay\n"
         "         and the minimap's match marks each worked out a column by walking the\n"
         "         line from its start, once per match, which took 23 s a keystroke",
         perf=True),

    Scen("perf-multi-cursor", "mini/lines20k.txt",
         ["w:2500", "k:" + CTRL_A, "w:1200", "k:" + ALT_SHIFT_I, "w:1500", "d",
          "k:Z", "w:1500", "d", "k:" + CTRL_Z, "w:1500", "d"],
         "one keystroke with a cursor on every line of a 20,000 line file. Each\n"
         "         cursor copied the other 19,999 in and out of T->mc and moved\n"
         "         them one at a time, so one letter took 3 s here and 20-40 s on\n"
         "         a 50,000 line file. The second dump is the guard: an mme still\n"
         "         busy with the keystroke has not drawn the Z, and the third\n"
         "         shows one Ctrl+Z taking every one of them back",
         perf=True),

    Scen("nes-gutter-arrow", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 5, "w:2000", "d"] + brows(20, 21),
         "a next edit seven lines below the cursor: the gutter carries an arrow on "
         "its line, the bytes it would replace are tinted like a removed line and "
         "what it would put there is a dim row under them, tinted like an added one",
         stub_lsp=("c",)),
    Scen("nes-tab-jumps-then-applies", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 5, "w:2000", "d",
          "k:" + TAB, "w:900", "d", "k:" + TAB, "w:900", "d"],
         "Tab takes the cursor to the next edit and leaves it showing; Tab again "
         "puts it into the text, the line changes and the tab goes dirty - and the "
         "event loop keeps its tick while a next edit is on the screen",
         stub_lsp=("c",), perf=True),
    Scen("nes-esc-dismisses", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 5, "w:2000", "d",
          "k:" + ESC, "w:900", "d", "w:2500", "d"],
         "Esc drops the next edit: the arrow, the tint and the row under it all go, "
         "and it does not come back on its own",
         stub_lsp=("c",)),
    Scen("nes-above-the-cursor", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 21, "w:2000", "d"] + brows(15, 16),
         "an edit above the cursor is pointed at where it is, not at the cursor",
         stub_lsp=("c",)),
    Scen("nes-offscreen-below", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 3, "w:2000", "d"],
         "an edit past the last line the screen shows puts an arrow pointing down at "
         "the bottom edge, and the view is not scrolled to it",
         stub_lsp=("c",)),
    Scen("nes-offscreen-above", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 35, "w:2000", "d"],
         "an edit above the top of a scrolled view puts an arrow pointing up at the "
         "top edge, and the view stays where it is",
         stub_lsp=("c",)),
    Scen("nes-ghost-text-wins", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 11, "w:2500", "d"] + arows(14) +
         ["k:" + ESC, "w:900", "d", "k:" + UP * 6, "w:2000", "d"],
         "where the server offers both a continuation at the cursor and an edit "
         "elsewhere, the cursor's wins: the ghost text is dim on the line and "
         "nothing points anywhere else. One Esc puts both away - the edit the "
         "server had already sent does not step forward - and moving the cursor "
         "asks again, so the edit for the new place appears",
         stub_lsp=("c",)),
    Scen("nes-notifications", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 17, "w:1500", "d",
          "k:" + TAB, "k:" + TAB, "w:700", "d"],
         "mme tells the server what it did with the edit: didShowInlineEdit when it "
         "draws it, the edit's own command and reportCachedInlineEdit \"accepted\" "
         "when Tab takes it - the stub echoes each one back as a message",
         stub_lsp=("c",)),
    Scen("nes-setting-off-then-on", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 5, "w:2000", "d",
          "k:" + CTRL_SHIFT_P, "k:Toggle Next Edit", "w:600", "k:|", "w:2500", "d"],
         "github.copilot.nextEditSuggestions.enabled false offers nothing at all, "
         "and the palette command that turns it back on makes the edit appear",
         stub_lsp=("c",),
         settings={"github.copilot.nextEditSuggestions.enabled": False}),
    Scen("nes-palette-commands", "lang/edit.c",
         ["w:1500", "k:" + CTRL_SHIFT_P, "k:Next Edit", "w:900", "d"],
         "the palette carries the next edit commands, whether or not a server is set"),

    Scen("lsp-latin1-source", "lang/latin1.c",
         ["w:3000", "k:" + CTRL_SHIFT_M, "w:1200", "d"],
         "a source file with Latin-1 bytes in it still reaches the language\n"
         "         server. A JSON message is UTF-8: a raw 0xE9 inside one makes every\n"
         "         strict reader (Python's json, llvm::json in clangd) throw the whole\n"
         "         message away, and the file loses IntelliSense for good - PROBLEMS\n"
         "         would be empty and the server would be restarting in a loop",
         stub_lsp=("c",)),
    Scen("lsp-language-mode-server", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_P, "k:Change Language Mode", "w:700",
          "k:|", "w:700", "k:Python", "w:700", "k:|", "w:3000",
          "k:" + CTRL_SHIFT_M, "w:1200", "d"],
         "Change Language Mode hands the file to the new language's server:\n"
         "         PROBLEMS carries the Python server's diagnostics. The file used to\n"
         "         stay on the server of the language it was opened as, for the whole\n"
         "         session, and Copilot kept being told the old languageId",
         settings={"mme.languageServers": {"*": "",
                                           "c": stub_cmd("--name=c-server"),
                                           "python": stub_cmd("--name=py-server")}}),
    Scen("copilot-signin-expires", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_P, "k:GitHub Copilot: Sign In", "w:900",
          "k:|", "w:3000",	# past the second the code lasts, and past the toast
          "k:" + CTRL_SHIFT_P, "k:GitHub Copilot: Sign In", "w:1000",
          "k:|", "w:1400", "d"],
         "a device flow the server never finishes is given up on once the code\n"
         "         it named has expired, so Sign In works again and offers a new one.\n"
         "         Nothing else ever cleared it: one closed browser tab used to leave\n"
         "         'a sign-in is already running' for as long as the editor ran",
         inline_lsp="stuck", fake_browser=True),
    Scen("copilot-signin-twice", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_P, "k:GitHub Copilot: Sign In", "w:400",
          "k:|", "w:400",
          "k:" + CTRL_SHIFT_P, "k:GitHub Copilot: Sign In", "w:400",
          "k:|", "w:1200", "d"],
         "two Sign Ins in a row send the server one signIn, not two: it says how\n"
         "         many it was asked for, and two device flows would mean two codes of\n"
         "         which only the second is on the screen and on the clipboard",
         inline_lsp="slow", fake_browser=True),
    # --------------------------------------------------- files mme must not eat
    # --------------------------------------------------- files mme must not eat
    Scen("merge-close-keeps-file", "odd/selfmerge.c",
         ["w:1500", "k:^Q", "w:1500"],
         "quitting the merge editor must leave the file alone. A conflict with an\n"
         "         empty side needs no resolving, and completing the merge on the way\n"
         "         out rewrote the file with no dialog and no undo",
         private=True, watch=("selfmerge.c",)),
    Scen("encoding-utf16-is-text", "odd/utf16le.txt",
         ["w:2000", "d"],
         "a UTF-16 file opens as text, with UTF-16 LE in the status bar. Its NUL\n"
         "         bytes used to make it 'binary', so it opened read-only in the hex\n"
         "         editor although the encoding is fully implemented"),
    Scen("find-regex-backtrack", "odd/aaa.txt",
         ["w:1500", "k:" + CTRL_F, "w:400", "k:" + ALT_R, "w:400",
          "k:(a+)+$", "w:4000", "d"],
         "a backtracking pattern over a 60 KB line leaves mme alive and drawing\n"
         "         instead of running the C stack out: the matcher used to recurse once\n"
         "         per repetition. How far it gets before it gives up depends on the\n"
         "         stack it has left, so the cursor and selection are masked",
         subs=[(re.compile(r"Ln \d+, Col \d+( \(\d+ selected\))?"), "Ln -, Col -")]),

    # ------------------------------ the language-server surfaces, from a stub
    # reg/stublsp.py always answers the same thing, so what mme draws from a
    # language server can be pinned without one being installed.
    Scen("lsp-codelens-and-hints", "lang/edit.c",
         ["w:3000", "d"] + crows(17, 18, 19, 20, 21) + arows(17, 18, 19, 20, 21),
         "the code lens row over a function, and the dim italic inlay hint in a line",
         stub_lsp=("c",)),
    Scen("lsp-problems", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_M, "w:1200", "d"],
         "PROBLEMS lists the server's diagnostics, and the status bar counts them",
         stub_lsp=("c",)),
    Scen("lsp-squiggles", "lang/edit.c",
         ["w:3000"] + arows(15, 16, 32, 33) + crows(15, 32),
         "the curly underline under a diagnostic, and the gutter mark beside it",
         stub_lsp=("c",)),
    Scen("lsp-hover", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 15, "k:" + RIGHT * 12,
          "k:" + CTRL_K, "k:" + csiu("i", ctrl=True), "w:1200", "d"],
         "Ctrl+K Ctrl+I shows the server's hover over the name at the cursor",
         stub_lsp=("c",)),
    Scen("lsp-pull-diagnostics", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_M, "w:1200", "d"] + click(40, 6) +
         ["k:x", "w:1000", "d", "w:3500", "d"],
         "a server with diagnosticProvider is asked for the problems (textDocument/\n"
         "         diagnostic) and PROBLEMS lists them, the related document's too; after\n"
         "         an edit the pull sends the last resultId and \"unchanged\" keeps them;\n"
         "         workspace/diagnostic/refresh pulls again and the new ones replace them",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--pull")}}),
    Scen("lsp-color-decorators", "lsp/colors.c",
         ["w:3000", "d"] + crows(4, 5, 6, 7),
         "a swatch in each color the server finds is drawn before it, the text after\n"
         "         it moved right like an inlay hint's (the faded one mixed with the\n"
         "         background by its alpha)",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--colors")}}),
    Scen("lsp-color-picker", "lsp/colors.c",
         ["w:3000"] + click(32, 6) + ["w:1000", "d", "k:" + DOWN, "k:|", "w:1500", "d"],
         "a click on a swatch lists the server's color presentations, the current one\n"
         "         marked, and picking one writes the color that way (its textEdit)",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--colors")}}),
    Scen("lsp-color-picker-hex", "lsp/colors.c",
         ["w:3000", "k:" + DOWN + RIGHT * 20, "k:" + CTRL_SHIFT_P,
          "k:Show or Focus Standalone Color Picker", "w:700", "k:|", "w:1000", "d",
          "k:#00f", "w:500", "k:|", "w:1500", "d"],
         "Show or Focus Standalone Color Picker at a color opens its picker, and a hex\n"
         "         color typed there is written in the format the color had (#0000ff)",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--colors")}}),
    Scen("lsp-links-ctrl-hover", "lsp/links.c",
         ["w:3000", "k:`[<51;25;6M", "w:600", "d", "a:5"],
         "Ctrl+hover over a document link underlines the whole link (a URL), not\n"
         "         just the word under the mouse",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--links")}}),
    Scen("lsp-links-ctrl-click", "lsp/links.c",
         ["w:3000", "k:`[<16;22;5M", "k:`[<16;22;5m", "w:1500", "d"],
         "Ctrl+Click on a document link opens its file at the line and column of\n"
         "         its #L4,14 fragment (colors.c, line 4), instead of Go to Definition",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--links")}}),
    Scen("lsp-links-resolve", "lsp/links.c",
         ["w:3000", "k:`[<16;22;7M", "k:`[<16;22;7m", "w:1500", "d"],
         "a document link with no target is resolved (documentLink/resolve) when it\n"
         "         is Ctrl+Clicked, and then opened: renamer/main.c at line 4",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--links")}}),
    Scen("lsp-rename-updates-imports", "lsp/renamer",
         ["w:1800"] + click(12, 6) + ["w:2500"] + click(12, 7) +
         ["w:700", "k:`OQ", "w:500", "k:helper", "w:300", "k:|", "w:1500", "d"] +
         click(38, 2) + ["w:1500", "d"],
         "renaming a header in the Explorer asks the server first (workspace/\n"
         "         willRenameFiles, its filter **/*.{h,hpp}) and makes its edit - the\n"
         "         #include in main.c now names helper.h, the tab dirty, not saved - then\n"
         "         the file moves and the server is told (didRenameFiles, echoed)",
         settings={"mme.languageServers": {"*": "", "c": stub_cmd("--rename")}},
         private=True, watch=("renamer/util.h", "renamer/helper.h", "renamer/main.c")),

    # ------------------------------------------------------------------ panel
    Scen("lsp-inline-ghost", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 11, "w:1500", "d"] + arows(14),
         "the server's continuation is drawn dim where it would go and is not in the file: "
         "the tab has no dirty dot and the status bar still says Ln 12, Col 1",
         stub_lsp=("c",)),
    Scen("lsp-inline-tab-accepts", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 11, "w:1500", "k:" + TAB, "w:900", "d"] + arows(14),
         "Tab puts the whole suggestion into the text: the line has it, the tab is dirty, "
         "and nothing is dim any more",
         stub_lsp=("c",)),
    Scen("lsp-inline-esc-dismisses", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 11, "w:1500", "d"] + arows(14) +
         ["k:" + ESC, "w:900", "d"] + arows(14) + ["w:2000", "d"],
         "Esc drops the suggestion: the line is blank again, nothing is dim, "
         "and it does not come back on its own",
         stub_lsp=("c",)),
    Scen("lsp-inline-accept-word", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 11, "w:1500", "k:`[1;5C", "w:900", "d"] + arows(14),
         "Ctrl+Right puts one word of the suggestion in and leaves the rest of it dim",
         stub_lsp=("c",)),
    Scen("lsp-inline-cycle", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 13, "w:1500", "d",
          "k:" + csiu("]", alt=True), "w:900", "d",
          "k:" + csiu("[", alt=True), "w:900", "d"],
         "Alt+] and Alt+[ go through the candidates the server sent",
         stub_lsp=("c",)),
    Scen("lsp-inline-multiline", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 19, "w:1500", "d"] + arows(23, 24, 25),
         "a suggestion of several lines takes rows of its own and pushes the lines under it down",
         stub_lsp=("c",)),
    Scen("lsp-inline-tab-still-indents", "lang/edit.c",
         ["w:3000", "k:" + DOWN * 5, "k:" + END, "w:1500", "k:" + TAB, "w:900", "d"],
         "where the server offers nothing, Tab indents as it always did: "
         "inline suggestions never take Tab away from the editor",
         stub_lsp=("c",)),

    # ------------------------- GitHub Copilot: signing in, and the status item
    # stublsp.py doubles as Copilot's language server here: --auth= says which
    # account state it pretends to be in, it sends didChangeStatus the way
    # Copilot's does, and its device-flow command answers from a thread of its
    # own after a second - so an editor that blocked on the sign-in would show
    # as a screen that never changes. The Copilot item sits at column 116 of
    # the status bar, between the language and the notification bell.
    Scen("copilot-status-signed-out", "lang/edit.c",
         ["w:3000", "d", "a:29"],
         "the status bar carries a GitHub Copilot item, and it is drawn dim while "
         "the inline-completion server says nobody is signed in",
         inline_lsp="out"),
    Scen("copilot-status-menu", "lang/edit.c",
         ["w:3000"] + click(116, 30) + ["w:900", "d"],
         "a click on the Copilot status item opens its menu, and the menu offers "
         "Sign In while there is nobody signed in",
         inline_lsp="out"),
    Scen("copilot-status-busy", "lang/edit.c",
         ["w:3000", "d", "a:29"],
         "while the server says it is busy the item shows the working glyph instead "
         "of the suggestion one, and is not dim",
         inline_lsp="busy"),
    Scen("copilot-status-error", "lang/edit.c",
         ["w:3000", "k:`[<35;116;30M", "w:1400", "d", "a:29"],
         "an Error status draws the error icon in the status bar and puts the "
         "server's own message in the item's hover",
         inline_lsp="error"),
    Scen("copilot-signin-device-flow", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_P, "k:GitHub Copilot: Sign In", "w:600",
          "k:|", "w:700", "d", "a:29"],
         "GitHub Copilot: Sign In shows the device code and the page to type it in, "
         "and the item turns to the working icon while the flow is out",
         inline_lsp="out", fake_browser=True),
    Scen("copilot-signin-completes", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_P, "k:GitHub Copilot: Sign In", "w:600",
          "k:|", "w:6500", "d", "a:29"] + click(116, 30) + ["w:900", "d"],
         "when the device flow answers the item stops being dim and its menu names "
         "who is signed in and offers Sign Out - and the editor drew all the while "
         "the flow was out",
         inline_lsp="out", fake_browser=True),
    Scen("copilot-signout", "lang/edit.c",
         ["w:3000", "k:" + CTRL_SHIFT_P, "k:GitHub Copilot: Sign Out", "w:600",
          "k:|", "w:900", "d", "a:29"],
         "GitHub Copilot: Sign Out signs out of the server and the item goes dim "
         "again (the stub server only: never the real account)",
         inline_lsp="in"),
    Scen("copilot-status-v2", "lang/edit.c",
         ["w:3000"] + click(116, 30) + ["w:900", "d"],
         "the account and the status read out of didChangeStatus/v2 alone, the "
         "shape copilot-language-server 1.551 sends: the menu names the user "
         "although checkStatus answered nothing",
         inline_lsp="v2"),
    Scen("copilot-palette-commands", "lang/edit.c",
         ["w:1500", "k:" + CTRL_SHIFT_P, "k:GitHub Copilot", "w:900", "d"],
         "the palette carries the three GitHub Copilot commands, whether or not an "
         "inline-completion server is set"),

    # ------------------------------------------ Chat and Inline Chat (Claude)
    # stubclaude.py plays Anthropic's Messages API on a free local port: it
    # checks the request as the API would (headers, model, fallbacks, roles)
    # and streams a canned answer in pieces. No scenario can reach the real
    # API: run_once() drops ANTHROPIC_* from the environment, and the key is
    # a dummy. The Chat view opens at the right of the editors, columns
    # 86-119; its box to type in is at the bottom.
    Scen("chat-open-welcome", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:900", "d"],
         "Ctrl+Alt+I opens the Chat view in the secondary side bar: its title with "
         "New Chat and close, the welcome, and the box with the current file's chip",
         stub_claude="ok"),
    Scen("chat-missing-key", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:900", "d", "k:hello", "k:|", "w:900", "d"],
         "with no API key anywhere the view says how to set one, and asking "
         "sends nothing: it answers with the same notice"),
    Scen("chat-send-streamed", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:700", "k:How do I double a number?", "w:300", "d",
          "k:|", "w:3500", "d"] + crows(13, 14, 15, 16, 17),
         "a question goes to the API with the lines the editor shows, and the answer "
         "streams in as Markdown: bold, a list, and a C code block in C's colors "
         "with Copy, Insert and Apply on its top row; the thinking block is not shown",
         stub_claude="ok"),
    Scen("chat-two-turns", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:700", "k:first|", "w:3500",
          "k:second|", "w:3500", "d"],
         "a second question sends the whole talk again, roles taking turns: the stub "
         "counts two questions and says Answer 2",
         stub_claude="ok"),
    Scen("chat-selection-context", "lang/edit.c",
         ["w:1500", "k:" + DOWN * 15, "k:" + SH_DOWN * 3, "k:" + CTRL_ALT_I, "w:700", "d",
          "k:what does it do|", "w:3500", "d"],
         "the selection is the implicit context: the chip says edit.c:16-18 and the "
         "API is told those lines",
         stub_claude="ok"),
    Scen("chat-code-insert", "lang/edit.c",
         ["w:1500", "k:" + DOWN * 4, "k:" + CTRL_ALT_I, "w:700", "k:helper please|", "w:3500"] +
         click(107, 15) + ["w:900", "d"],
         "a code block's Insert puts its code at the editor's cursor, as a paste: "
         "the lines are in the file and its tab is dirty",
         stub_claude="ok"),
    Scen("chat-code-apply", "lang/edit.c",
         ["w:1500", "k:" + DOWN * 15, "k:" + SH_DOWN * 4, "k:" + CTRL_ALT_I, "w:700",
          "k:make it a helper|", "w:3500"] + click(114, 15) + ["w:900", "d",
          "k:" + CTRL_ENTER, "w:900", "d"],
         "a code block's Apply shows it in place of the selection as a diff, with "
         "Accept and Discard, and the editor has the keys: Ctrl+Enter puts it in",
         stub_claude="ok"),
    Scen("chat-new-chat", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:700", "k:first|", "w:3500",
          "k:" + csiu("l", ctrl=True), "w:700", "d"],
         "Ctrl+L in the view starts a new chat: the talk goes, the welcome is back",
         stub_claude="ok"),
    Scen("chat-http-401", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:700", "k:hi|", "w:2500", "d"],
         "a key the API refuses is told in words in the talk, not as raw JSON",
         stub_claude="401"),
    Scen("chat-overloaded", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:700", "k:hi|", "w:2500", "d"],
         "an overloaded API (529) is told as such, with try again",
         stub_claude="529"),
    Scen("chat-refusal", "lang/edit.c",
         ["w:1500", "k:" + CTRL_ALT_I, "w:700", "k:hi|", "w:2500", "d"],
         "stop_reason refusal is a short notice that Claude declined",
         stub_claude="refusal"),
    Scen("chat-inline-accept", "lang/edit.c",
         ["w:1500", "k:" + DOWN * 15, "k:" + SH_DOWN * 4, "k:" + CTRL_I, "w:700", "d",
          "k:use long", "k:|", "w:3000", "d", "k:" + CTRL_ENTER, "w:900", "d"],
         "Ctrl+I asks for a change of the selection in a box over it; the answer is a "
         "diff in the text (old tinted, new under it) with Accept and Discard, and "
         "Ctrl+Enter puts it in",
         stub_claude="ok"),
    Scen("chat-inline-discard", "lang/edit.c",
         ["w:1500", "k:" + DOWN * 15, "k:" + SH_DOWN * 4, "k:" + CTRL_I, "w:700",
          "k:use long", "k:|", "w:3000", "k:" + ESC, "w:900", "d"],
         "Esc throws Inline Chat's diff away: the file is as it was and not dirty",
         stub_claude="ok"),
    Scen("chat-palette-commands", "lang/edit.c",
         ["w:1500", "k:" + CTRL_SHIFT_P, "k:Chat", "w:900", "d"],
         "the palette carries Chat's and Inline Chat's commands by VS Code's names"),

    # ------------------------------------------------------------------ panel
    Scen("panel-terminal", "lang/edit.c",
         ["w:900", "k:" + CTRL_BACKTICK, "w:2500", "d",
          "k:echo REGRESSION_MARKER|", "w:2000", "d"],
         "the panel's TERMINAL runs a shell and shows what it printed"),
    Scen("panel-problems", "lang/edit.c",
         ["w:900", "k:" + CTRL_SHIFT_M, "w:900", "d"],
         "the panel's PROBLEMS tab"),
    Scen("panel-output", "lang/edit.c",
         ["w:900", "k:" + CTRL_SHIFT_U, "w:1200", "d"],
         "the panel's OUTPUT tab and its channel"),

    # ------------------------------------------------------------------ pages
    Scen("page-settings", "lang/edit.c",
         ["w:900", "k:" + CTRL_COMMA, "w:1500", "d"],
         "the Settings editor: the tree on the left and the controls on the right"),
    Scen("page-settings-search", "lang/edit.c",
         ["w:900", "k:" + CTRL_COMMA, "w:1200", "k:minimap", "w:1200", "d"],
         "searching the Settings editor narrows it to the matching settings"),
    Scen("page-keybindings", "lang/edit.c",
         ["w:900", "k:" + CTRL_K, "k:" + CTRL_S, "w:1200", "d",
          "k:palette", "w:800", "d"],
         "the Keyboard Shortcuts list and its search"),

    # ------------------------------------------------------------------- view
    Scen("view-wordwrap", "lang/wrap.js",
         ["w:1000", "d", "k:" + ALT_Z, "w:600", "d", "k:" + ALT_Z, "w:600", "d"],
         "Alt+Z wraps the long lines and unwraps them again"),
    Scen("colour-plain-text", "lang/plain.txt",
         ["w:2500", "d"] + crows(3, 4, 8, 12),
         "a file with no language: every cell, the minimap's included, takes a\n"
         "         colour from the theme. Stray colours here mean the token buffer\n"
         "         was read before anything filled it"),
    Scen("view-minimap", "mini/big.c",
         ["w:1200", "d", "k:" + CTRL_SHIFT_P, "w:300", "k:minimap", "w:600",
          "k:|", "w:900", "d"],
         "the minimap's braille column, and the command that turns it off"),
    Scen("view-sticky-scroll", "lang/sticky.c",
         ["w:1000", "k:" + PGDN, "w:600", "d", "k:" + PGDN, "w:600", "d"],
         "editor.stickyScroll: the enclosing scopes pinned over the text"),
    Scen("view-folding", "lang/fold.c",
         ["w:1000", "k:" + CTRL_K, "k:" + CTRL_0, "w:700", "d",
          "k:" + CTRL_K, "k:" + csiu("j", ctrl=True), "w:700", "d"],
         "Ctrl+K Ctrl+0 folds every block to its first line with the ... marker, Ctrl+K Ctrl+J unfolds"),
    Scen("view-md-preview", "lang/doc.md",
         ["w:1000", "k:" + CTRL_SHIFT_V, "w:1500", "d"],
         "the Markdown preview: headings, lists, the quote, the fence and the table"),
    Scen("view-sidebar-toggle", "proj",
         ["w:1800", "k:" + CTRL_B, "w:700", "d", "k:" + CTRL_B, "w:700", "d"],
         "Ctrl+B hides the side bar and the editor takes the width"),

    # ------------------------------------------------------------- Vim mode
    # vim.enable on: VSCodeVim's keys. Row 29 is the status bar, where the mode,
    # the keys of a command not finished yet, and the : and / lines show.
    Scen("vim-modes-status", "vim/text.txt",
         ["w:1200", "c:29", "k:i", "c:29", "k:" + ESC, "c:29", "k:v", "c:29",
          "k:V", "c:29", "k:^V", "c:29", "k:" + ESC, "k:R", "c:29", "k:" + ESC,
          "k:d2", "c:29", "k:" + ESC, "k::set nu", "c:29", "k:" + ESC,
          "k:qa", "c:29", "k:q", "k::bogus|", "c:29", "d"],
         "the mode in the status bar as VSCodeVim writes it (-- NORMAL --,\n"
         "         -- INSERT --, the three VISUALs, -- REPLACE --), the keys of a\n"
         "         command not whole yet, the : line, recording @a, and E492",
         settings={"vim.enable": True}),
    Scen("vim-motions-counts", "vim/text.txt",
         ["w:1200", "k:3w", "c:29", "k:2e", "c:29", "k:ge", "c:29", "k:$", "c:29",
          "k:b", "c:29", "k:0fo", "c:29", "k:;", "c:29", "k:,", "c:29", "k:tz", "c:29",
          "k:2j", "c:29", "k:0f(%", "c:29", "k:}", "c:29", "k:{", "c:29", "k:G", "c:29",
          "k:gg", "c:29", "k:5G", "c:29", "k:k" + csiu("^"), "c:29", "k:2W", "c:29", "k:e", "c:29"],
         "w b e ge $ 0 ^ f t ; , % { } G gg with counts land where Vim puts the\n"
         "         cursor (Ln, Col in the status bar after each)",
         settings={"vim.enable": True}),
    Scen("vim-operators-objects", "vim/text.txt",
         ["w:1200", "k:wd3w", "k:jgUiw", "k:jf(di(", "k:f\"ci\"X" + ESC, "k:j>>",
          "k:jjdap", "k:gg0daw", "k:jc$ZZ" + ESC, "w:300", "d"],
         "operators with motions and text objects: d3w gUiw di( ci\" >> dap daw c$",
         settings={"vim.enable": True}),
    Scen("vim-visual-line", "vim/text.txt",
         ["w:1200", "k:Vj", "w:200", "d", "k:y", "k:8Gp", "w:300", "d",
          "k:ggVjd", "k:jP", "w:300", "d"],
         "Visual Line mode: the lines lit, yanked, put after the last line,\n"
         "         deleted and put back above",
         settings={"vim.enable": True}),
    Scen("vim-visual-block", "vim/text.txt",
         ["w:1200", "k:^Vjjll", "w:600", "d", "k:d", "k:^VjjI// " + ESC, "w:300",
          "k:gg$^VjjA;" + ESC, "w:300", "d"],
         "Visual Block mode: the block drawn with a cursor per line, d, and I / A\n"
         "         typing on every line at once (A after $ at each line's end)",
         settings={"vim.enable": True}),
    Scen("vim-dot-repeat", "vim/text.txt",
         ["w:1200", "k:dw", "k:..", "k:jA!" + ESC, "k:j.", "k:jwciwNEW" + ESC,
          "k:w.", "k:3G3ia-" + ESC, "k:j.", "k:6GVd", "k:.", "w:300", "d"],
         ". repeats the last change: a delete, an append with what was typed, a\n"
         "         change of a word, an insert with a count, a Visual Line delete",
         settings={"vim.enable": True}),
    Scen("vim-undo-redo", "vim/text.txt",
         ["w:1200", "k:dd", "k:jciwONE" + ESC, "k:3ia-" + ESC, "w:200", "d",
          "k:u", "w:200", "d", "k:uu", "w:200", "d", "k:^R^R", "w:300", "d"],
         "u and Ctrl+R: each command and each visit to Insert mode is one step",
         settings={"vim.enable": True}),
    Scen("vim-search", "vim/text.txt",
         ["w:1200", "k:/fo", "w:300"] + brows(3, 6) + ["c:29", "k:|", "w:200"] +
         brows(3, 6) + ["c:29", "k:n", "c:29", "k:n", "c:29", "k:N", "c:29",
                        "k:gg*", "c:29", "k:/nothing|", "c:29"],
         "/ lights every match as it is typed and moves to the first; Enter keeps\n"
         "         it (the lights go: vim.hlsearch is off); n N * go on; E486",
         settings={"vim.enable": True}),
    Scen("vim-substitute", "vim/text.txt",
         ["w:1200", "k::%s/foo/BAR/g|", "k::2,3s/\\(t\\w*\\)/<\\1>/|",
          "k::6,8s/" + csiu("^") + "/# /|", "w:300", "d"],
         ":s with ranges: % every line and g every match, a group put back with\n"
         "         \\1, and an empty match at the start of each line (the last line's\n"
         "         message is Vim's: 3 substitutions on 3 lines)",
         settings={"vim.enable": True}),
    Scen("vim-write", "vim/text.txt",
         ["w:1200", "k:dd", "k::w|", "w:800", "d"],
         ":w saves the file: its first line is gone on disk and the tab is clean",
         settings={"vim.enable": True}, private=True, watch=("text.txt",)),
    Scen("vim-macros", "vim/text.txt",
         ["w:1200", "k:qaI# " + ESC, "k:jq", "c:29", "k:2@a", "k:@@", "w:300", "d"],
         "q records the keys (recording @a), @a plays them twice, @@ once more",
         settings={"vim.enable": True}),
    Scen("vim-toggle-command", "vim/text.txt",
         ["w:1200", "c:29", "k:" + CTRL_SHIFT_P, "w:300", "k:Vim: Toggle Vim Mode",
          "w:400", "k:|", "w:400", "c:29", "k:dd", "w:300", "d"],
         "Vim is off by default; Vim: Toggle Vim Mode turns it on and dd deletes"),
]


# ------------------------------------------------------------------- masking

def path_rx(root):
    """the directory as it may be printed: either slash, and what follows"""
    parts = [p for p in re.split(r"[\\/]", root) if p != ""]
    body = r"[\\/]".join(re.escape(p) for p in parts)
    return re.compile(body + r"[A-Za-z0-9_:.~+\\/-]*", re.I)


def build_masks():
    """Everything that would differ between two machines or two minutes."""
    subs = []
    # the directories this suite runs out of, as real paths rather than a
    # guessed-at name: the guess once matched every word holding a "w"
    # the shell inside the terminal panel prints its own spelling of the
    # temp directory, /tmp/<name>, which no Windows form of it matches
    subs.append((path_rx("/tmp/" + os.path.basename(BUILD)), "<PATH>"))
    # a path the view cut off before its end is still a path
    subs.append((re.compile(r"[A-Za-z]:[\\/][A-Za-z0-9_.~+\\/-]*[\\/]mme-test[A-Za-z0-9_.~+\\/-]*"), "<PATH>"))
    subs.append((re.compile(r"/tmp/[A-Za-z0-9_.~+/-]*"), "<PATH>"))
    for root in (BUILD, HERE, EDITOR):
        subs.append((path_rx(root), "<PATH>"))
        posix = "/" + root[0].lower() + root[2:].replace("\\", "/") if root[1:2] == ":" else root
        subs.append((path_rx(posix), "<PATH>"))
    # a path that the shell's prompt wrapped onto the next row keeps only its tail
    subs.append((re.compile(r"[A-Za-z0-9_.~+-]*[\\/](?:reg|fix|work|golden)[\\/][A-Za-z0-9_.\\/-]*"),
                 "<PATH>"))
    for var, tag in (("USERNAME", "<USER>"), ("COMPUTERNAME", "<HOST>"),
                     ("USERDOMAIN", "<DOMAIN>")):
        v = os.environ.get(var)
        if v:
            subs.append((re.compile(re.escape(v), re.I), tag))
    # "2 years ago" in git blame and the history list
    subs.append((re.compile(r"\b\d+ (?:second|minute|hour|day|week|month|year)s? ago"),
                 "<AGO>"))
    subs.append((re.compile(r"\b(?:just now|seconds ago)\b"), "<AGO>"))
    # the OUTPUT channel's timestamps and command timings
    subs.append((re.compile(r"\d{4}-\d\d-\d\d \d\d:\d\d:\d\d"), "<DATETIME>"))
    subs.append((re.compile(r"\[\d+(?:\.\d+)?m?s\]"), "[<MS>]"))
    subs.append((re.compile(r"\b\d\d:\d\d(?::\d\d)?\b"), "<TIME>"))
    # the shell's own version, which is not ours to pin
    subs.append((re.compile(r"mmc \d+\.\d+\.\d+"), "mmc <VER>"))
    return subs


MASKS = build_masks()


def normalise(text, extra):
    for rx, rep in MASKS + list(extra):
        text = rx.sub(rep, text)
    # trailing blanks never carry meaning and the terminal pads with them
    return "".join(line.rstrip() + "\n" for line in text.splitlines())


# ------------------------------------------------------------------- running

def load_seed():
    raw = io.open(SEED, encoding="utf-8").read()
    raw = "\n".join(l for l in raw.splitlines() if not l.lstrip().startswith("//"))
    return json.loads(raw)


SEED_JSON = load_seed()


def _chmod_retry(fn, path, exc):
    os.chmod(path, stat.S_IWRITE)
    fn(path)


def wipe(path):
    """Windows holds an exe for a moment after it exits: try again, briefly."""
    for i in range(20):
        if not os.path.exists(path):
            return
        try:
            if os.path.isdir(path):
                shutil.rmtree(path, onerror=_chmod_retry)
            else:
                os.chmod(path, stat.S_IWRITE)
                os.unlink(path)
            return
        except OSError:
            time.sleep(0.1)
    raise SystemExit("cannot clear %s" % path)


def prepare(scen, exe_src, extra=None):
    """a private folder with its own mme.exe and its own empty mme-data"""
    d = os.path.join(WORK, scen.name)
    exe = os.path.join(d, "mme.exe")
    wipe(os.path.join(d, "mme-data"))
    wipe(os.path.join(d, "target"))
    os.makedirs(os.path.join(d, "mme-data"))
    src = os.stat(exe_src)
    if not os.path.isfile(exe) or os.stat(exe).st_size != src.st_size             or os.stat(exe).st_mtime < src.st_mtime:
        wipe(exe)
        shutil.copyfile(exe_src, exe)
    conf = dict(SEED_JSON)
    conf.update(scen.settings)
    conf.update(extra or {})
    stub = "python " + os.path.join(HERE, "stublsp.py").replace("\\", "/")
    if scen.stub_lsp:
        servers = dict(conf["mme.languageServers"])
        for lang in scen.stub_lsp:
            servers[lang] = stub
        conf["mme.languageServers"] = servers
    if scen.inline_lsp:
        conf["mme.inlineCompletionServer"] = stub + " --auth=" + scen.inline_lsp
    io.open(os.path.join(d, "mme-data", "settings.json"), "w", encoding="utf-8",
            newline="\n").write(json.dumps(conf, indent=2) + "\n")
    return d


def target_path(scen, work):
    src = scen.target if os.path.isabs(scen.target) else os.path.join(FIX, scen.target)
    if not scen.private:
        return src
    dst = os.path.join(work, "target", os.path.basename(src))
    if os.path.isdir(src):
        shutil.copytree(src, dst)
    else:
        os.makedirs(os.path.dirname(dst))
        shutil.copyfile(src, dst)
    return dst


# the key stubclaude.py wants; never a real one
STUB_CLAUDE_KEY = "sk-ant-test-dummy-key"


def start_stub_claude(mode):
    """stubclaude.py on a free port: (process, its base URL)"""
    p = subprocess.Popen([sys.executable, os.path.join(HERE, "stubclaude.py"), "--mode=" + mode],
                         stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    line = p.stdout.readline().decode("ascii", "replace").split()
    return p, "http://127.0.0.1:%s" % (line[1] if len(line) > 1 else "9")


def run_once(scen, use_prof):
    stub = None
    extra = {}
    if scen.stub_claude:
        stub, url = start_stub_claude(scen.stub_claude)
        extra = {"mme.chat.baseUrl": url, "mme.chat.apiKey": STUB_CLAUDE_KEY}
    try:
        return run_once_(scen, use_prof, extra)
    finally:
        if stub:
            stub.kill()
            stub.wait()


def run_once_(scen, use_prof, extra):
    work = prepare(scen, PBIN if use_prof else BIN, extra)
    tgt = target_path(scen, work)
    env = dict(os.environ)
    # the user's own Anthropic key must never reach a scenario: a chat that
    # found one would talk to the real API, and spend money doing it
    for k in ("ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_BASE_URL"):
        env.pop(k, None)
    log = os.path.join(work, "tick.log")
    env["MME_TICKLOG"] = log
    # nothing below may reach into the user's own git or VS Code configuration
    env["GIT_CONFIG_GLOBAL"] = os.path.join(FIX, "gitconfig-none")
    env["GIT_CONFIG_SYSTEM"] = os.path.join(FIX, "gitconfig-none")
    # this suite is inside the editor's own checkout, and a fixture that is
    # not meant to be in a repository must not find that one by walking up
    env["GIT_CEILING_DIRECTORIES"] = BUILD
    if scen.fake_browser:
        # mme opens a URL with "rundll32 url.dll,FileProtocolHandler <url>", and
        # find_program takes the first rundll32 on the PATH: this one writes the
        # URL to MME_URLLOG and exits, so no browser window is ever opened
        env["PATH"] = BROWSER + os.pathsep + env.get("PATH", "")
        env["MME_URLLOG"] = os.path.join(work, "urls.txt")
    cmd = [HARNESS, os.path.join(work, "mme.exe"), tgt] + scen.steps
    t0 = time.time()
    try:
        r = subprocess.run(cmd, env=env, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT, timeout=180)
        out = r.stdout
    except subprocess.TimeoutExpired:
        out = b"*** the harness did not finish in 180 s ***\n"
    took = time.time() - t0
    text = normalise(out.decode("utf-8", "replace"), scen.subs)
    text += watched(scen, work)
    ticks = read_ticks(log) if use_prof else None
    return text, ticks, took


def watched(scen, work):
    """What the run left of the files the scenario watches, as golden lines.
    A file mme must not touch shows its length and its first bytes; one that
    is gone says so."""
    out = ""
    for rel in scen.watch:
        p = os.path.join(work, "target", rel.replace("/", os.sep))
        if not os.path.isfile(p):
            out += "file %s: gone\n" % rel
            continue
        b = io.open(p, "rb").read()
        head = b[:40].decode("utf-8", "replace").replace("\n", "\\n").replace("\r", "\\r")
        out += "file %s: %d bytes, starts %s\n" % (rel, len(b), head)
    return out


BLANK_RX = re.compile(r"^(?:---- cursor [\d,]+|exited=\d+|\|\s*|[{\[<][0-9a-f-]*[}\]>]\s*)$")


def looks_blank(text):
    """True when mme drew nothing at all: it had not started yet, so the waits
    in the scenario were too short for how busy the machine was."""
    for line in text.splitlines():
        if not BLANK_RX.match(line):
            return False
    return True


# one draw of a 500 KB line is noisy: a cold cache or another process doubles
# it. A perf scenario is run a few times and the median is what counts.
PERF_REPS = 3


def median(v):
    v = sorted(v)
    return v[len(v) // 2]


def run_one(scen, use_prof, want=None):
    """want: the golden this run is compared against. A run that does not match
    it is tried once more before it is believed - see retry_note()."""
    if not use_prof:
        r = run_once(scen, False)
        if looks_blank(r[0]) or (want is not None and r[0] != want):
            r2 = run_once(scen, False)   # once more, with the machine less busy
            if looks_blank(r[0]):
                return r2 if not looks_blank(r2[0]) else r
            if r2[0] == want:
                FLAKY.append(scen.name)
                return r2
        return r
    runs = [run_once(scen, True) for _ in range(PERF_REPS)]
    text, _, _ = runs[0]
    ticks = {"max_us": median([r[1]["max_us"] for r in runs]),
             "over_20ms": median([r[1]["over_20ms"] for r in runs])}
    return text, ticks, sum(r[2] for r in runs)


FLAKY = []	# scenarios that failed once and passed on the retry


TICK_RX = re.compile(r"tick: total (\d+)")


def read_ticks(path):
    if not os.path.isfile(path):
        return {"max_us": 0, "over_20ms": 0}
    mx, n = 0, 0
    for line in io.open(path, encoding="utf-8", errors="replace"):
        m = TICK_RX.search(line)
        if m:
            n += 1
            mx = max(mx, int(m.group(1)))
    return {"max_us": mx, "over_20ms": n}


# ------------------------------------------------------------------ comparing

def golden_path(name):
    return os.path.join(GOLDEN, name + ".txt")


def read_golden(name):
    p = golden_path(name)
    if not os.path.isfile(p):
        return None
    # a checkout with core.autocrlf has them with CR LF; a screen never has a CR
    return io.open(p, encoding="utf-8", newline="").read().replace("\r\n", "\n")


def write_golden(name, text):
    if not os.path.isdir(GOLDEN):
        os.makedirs(GOLDEN)
    io.open(golden_path(name), "w", encoding="utf-8", newline="").write(text)


def diff(name, want, got):
    return "".join(difflib.unified_diff(
        want.splitlines(True), got.splitlines(True),
        fromfile="golden/%s.txt" % name, tofile="this run", n=2))


# a regression has to be caught, a slow machine has not: a scenario may take
# four times its baseline, but never less than this floor
PERF_FACTOR = 4.0
PERF_FLOOR_US = 150000
PERF_COUNT_FLOOR = 8


def perf_check(name, ticks, base):
    """-> (ok, message)"""
    b = base.get(name)
    if b is None:
        return True, "no baseline yet (--update records one)"
    lim_us = max(PERF_FACTOR * b["max_us"], PERF_FLOOR_US)
    lim_n = max(PERF_FACTOR * b["over_20ms"], PERF_COUNT_FLOOR)
    msg = ("max tick %d us (baseline %d, limit %d), ticks over %dms: %d "
           "(baseline %d, limit %d)" % (ticks["max_us"], b["max_us"], lim_us,
                                        TICK_MS, ticks["over_20ms"],
                                        b["over_20ms"], lim_n))
    return ticks["max_us"] <= lim_us and ticks["over_20ms"] <= lim_n, msg


# ---------------------------------------------------------------------- main

def sync_tree():
    """tree/ is the editor's sources as they are right now. Copying them here
    every build means the suite can never be measuring a stale tree."""
    if not os.path.isfile(os.path.join(EDITOR, "mme.c")):
        raise SystemExit("cannot find the editor's sources at %s" % EDITOR)
    if not os.path.isdir(TREE):
        os.makedirs(TREE)
    n = 0
    for name in os.listdir(EDITOR):
        if not name.endswith((".c", ".h", ".rc", ".ico")) and name not in ("build.bat", "makefile"):
            continue
        src = os.path.join(EDITOR, name)
        if not os.path.isfile(src):
            continue
        dst = os.path.join(TREE, name)
        same = (os.path.isfile(dst) and os.path.getsize(dst) == os.path.getsize(src)
                and os.path.getmtime(dst) >= os.path.getmtime(src))
        if not same:
            shutil.copyfile(src, dst)
            n += 1
    print("tree/ synced from %s (%d file(s) changed)" % (EDITOR, n))


def build(tree, dest):
    env = dict(os.environ)
    env["MME_DEST"] = dest
    if not os.path.isdir(dest):
        os.makedirs(dest)
    r = subprocess.run(["cmd.exe", "/c", os.path.join(tree, "build.bat")],
                       env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    sys.stdout.write(r.stdout.decode("utf8", "replace"))
    if r.returncode:
        raise SystemExit("build of %s failed" % tree)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--update", action="store_true", help="re-bless the goldens")
    ap.add_argument("-k", "--filter", default="", help="only names containing this")
    ap.add_argument("--repeat", type=int, default=1, help="run the suite N times")
    ap.add_argument("--jobs", type=int, default=8, help="scenarios at once")
    ap.add_argument("--list", action="store_true", help="print the scenarios")
    ap.add_argument("--build", action="store_true", help="rebuild bin/ and pbin/")
    args = ap.parse_args()

    if args.list:
        for s in SCENARIOS:
            print("%-28s %-22s %s" % (s.name, s.target, s.guards))
        return 0

    if args.build:
        sync_tree()
        import mkprof
        mkprof.main()                       # ptree/ from the sources just synced
        build(TREE, os.path.join(HERE, "bin"))
        build(PTREE, os.path.join(HERE, "pbin"))

    for p in (HARNESS, BIN, PBIN):
        if not os.path.isfile(p):
            raise SystemExit("%s is missing: run  python run.py --build" % p)
    if not os.path.isdir(FIX):
        raise SystemExit("fix/ is missing: run  python mkfix.py")

    todo = [s for s in SCENARIOS if args.filter in s.name]
    if not todo:
        raise SystemExit("no scenario matches %r" % args.filter)

    if not args.filter and os.path.isdir(GOLDEN):
        want = set(s.name + ".txt" for s in SCENARIOS) | set(["perf-baseline.json"])
        stale = sorted(set(os.listdir(GOLDEN)) - want)
        if stale:
            print("stale goldens, from scenarios that are gone: %s" % ", ".join(stale))

    base = {}
    if os.path.isfile(PERF_BASELINE):
        base = json.load(io.open(PERF_BASELINE, encoding="utf-8"))

    bad = 0
    first = {}
    new_base = dict(base)
    for pass_no in range(args.repeat):
        t0 = time.time()
        results = {}
        # the screens can all be driven at once; the perf scenarios are timed,
        # so they get the machine to themselves, one after the other
        quick = [s for s in todo if not s.perf]
        timed = [s for s in todo if s.perf]
        # a mismatch is retried once, but only when there is a golden to
        # compare with and no --repeat asking about determinism
        retry = not args.update and args.repeat == 1
        with ThreadPoolExecutor(max_workers=args.jobs) as ex:
            futs = {ex.submit(run_one, s, False,
                              read_golden(s.name) if retry else None): s for s in quick}
            for f, s in futs.items():
                results[s.name] = f.result()
        for s in timed:
            results[s.name] = run_one(s, True)
        fails = []
        for s in todo:
            text, ticks, took = results[s.name]
            tag = "" if args.repeat == 1 else " [pass %d]" % (pass_no + 1)
            if args.repeat > 1:
                if pass_no == 0:
                    first[s.name] = text
                elif first[s.name] != text:
                    fails.append((s, "NOT DETERMINISTIC between passes",
                                  diff(s.name + " (pass 1)", first[s.name], text)))
                    continue
            if args.update:
                write_golden(s.name, text)
                if s.perf:
                    new_base[s.name] = ticks
                print("blessed  %-30s %5.1fs%s%s" % (
                    s.name, took, tag,
                    ("  max tick %d us, %d over %dms" % (ticks["max_us"], ticks["over_20ms"], TICK_MS)) if s.perf else ""))
                continue
            want = read_golden(s.name)
            if want is None:
                fails.append((s, "no golden: run --update", ""))
                continue
            if want != text:
                fails.append((s, "the screen differs from the golden",
                              diff(s.name, want, text)))
                continue
            if s.perf:
                ok, msg = perf_check(s.name, ticks, base)
                if not ok:
                    fails.append((s, "the event loop got slower: " + msg, ""))
                    continue
                print("ok       %-30s %5.1fs%s  %s" % (s.name, took, tag, msg))
            else:
                print("ok       %-30s %5.1fs%s" % (s.name, took, tag))
        for s, why, d in fails:
            print("")
            print("FAIL     %s" % s.name)
            print("         guards: %s" % s.guards)
            print("         %s" % why)
            if d:
                for line in d.splitlines():
                    print("    " + line)
        bad += len(fails)
        print("")
        if FLAKY:
            print("flaky: %s - differed once, matched on the retry. The guard holds,"
                  % ", ".join(sorted(set(FLAKY))))
            print("       but the screen is being read before mme has settled.")
            del FLAKY[:]
        print("%d scenario(s), %d failed, %.1fs%s" % (
            len(todo), len(fails), time.time() - t0,
            "" if args.repeat == 1 else " (pass %d of %d)" % (pass_no + 1, args.repeat)))

    if args.update:
        io.open(PERF_BASELINE, "w", encoding="utf-8", newline="\n").write(
            json.dumps(new_base, indent=2, sort_keys=True) + "\n")
        print("perf baseline written to golden/perf-baseline.json")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
