/* enb_kernel.h - mme-kernel.py (enb.c writes it into mme-data), a line each: made from it, not edited here */
  "# mme's notebook kernel: runs the cells mme sends (one JSON line each, on\n",
  "# stdin), answers with JSON lines on stdout. A Jupyter kernel when\n",
  "# jupyter_client is installed (any language it knows), else this Python.\n",
  "#\n",
  "# mme -> kernel: {\"op\": \"exec\", \"id\", \"code\"}, {\"op\": \"interrupt\"},\n",
  "#   {\"op\": \"input\", \"value\"}, {\"op\": \"complete\", \"req\", \"code\", \"pos\"}\n",
  "# kernel -> mme: ready, log, stream, result, display, error, done (with the\n",
  "#   cell's id), input (a prompt), complete (req, matches, start, end)\n",
  "import sys, json, io, os, base64, threading, traceback, linecache, ast, queue, re\n",
  "\n",
  "OUT = sys.stdout\n",
  "LOCK = threading.Lock()\n",
  "\n",
  "\n",
  "def send(m):\n",
  "    with LOCK:\n",
  "        OUT.write(json.dumps(m) + \"\\n\")\n",
  "        OUT.flush()\n",
  "\n",
  "\n",
  "def lines():\n",
  "    for line in sys.stdin:\n",
  "        line = line.strip()\n",
  "        if line:\n",
  "            try:\n",
  "                yield json.loads(line)\n",
  "            except ValueError:\n",
  "                pass\n",
  "\n",
  "\n",
  "# ---------------------------------------------------------------- Jupyter\n",
  "def run_jupyter(name):\n",
  "    from jupyter_client.manager import KernelManager\n",
  "    km = KernelManager(kernel_name=name)\n",
  "    km.start_kernel()\n",
  "    kc = km.client()\n",
  "    kc.start_channels()\n",
  "    kc.wait_for_ready(timeout=120)\n",
  "    spec = name\n",
  "    try:\n",
  "        spec = km.kernel_spec.display_name\n",
  "    except Exception:\n",
  "        pass\n",
  "    send({\"type\": \"ready\", \"mode\": \"jupyter\", \"info\": spec})\n",
  "    jobs = queue.Queue()\n",
  "    comp_lock = threading.Lock()\n",
  "\n",
  "    def complete(m):\t# the shell channel's reply to complete_request\n",
  "        with comp_lock:\n",
  "            try:\n",
  "                r = kc.complete(m[\"code\"], m[\"pos\"], reply=True, timeout=5)\n",
  "                c = r[\"content\"]\n",
  "                send({\"type\": \"complete\", \"req\": m[\"req\"], \"matches\": c.get(\"matches\", [])[:200],\n",
  "                      \"start\": c.get(\"cursor_start\", m[\"pos\"]), \"end\": c.get(\"cursor_end\", m[\"pos\"])})\n",
  "            except Exception:\n",
  "                send({\"type\": \"complete\", \"req\": m[\"req\"], \"matches\": [], \"start\": m[\"pos\"], \"end\": m[\"pos\"]})\n",
  "\n",
  "    def reader():\t# interrupt, input, completions come while a cell runs\n",
  "        for m in lines():\n",
  "            op = m.get(\"op\")\n",
  "            if op == \"interrupt\":\n",
  "                km.interrupt_kernel()\n",
  "            elif op == \"input\":\n",
  "                kc.input(m.get(\"value\", \"\"))\n",
  "            elif op == \"complete\":\n",
  "                threading.Thread(target=complete, args=(m,), daemon=True).start()\n",
  "            elif op == \"exec\":\n",
  "                jobs.put(m)\n",
  "        jobs.put(None)\n",
  "\n",
  "    threading.Thread(target=reader, daemon=True).start()\n",
  "    while True:\n",
  "        m = jobs.get()\n",
  "        if m is None:\n",
  "            break\n",
  "        cid = m[\"id\"]\n",
  "        msg_id = kc.execute(m[\"code\"], allow_stdin=True)\n",
  "        count = None\n",
  "        while True:\n",
  "            try:\t# a prompt of input(): mme asks, its answer comes as op \"input\"\n",
  "                im = kc.get_stdin_msg(timeout=0)\n",
  "                if im[\"msg_type\"] == \"input_request\":\n",
  "                    send({\"id\": cid, \"type\": \"input\", \"prompt\": im[\"content\"].get(\"prompt\", \"\"),\n",
  "                          \"password\": im[\"content\"].get(\"password\", False)})\n",
  "            except Exception:\n",
  "                pass\n",
  "            try:\n",
  "                msg = kc.get_iopub_msg(timeout=0.1)\n",
  "            except Exception:\n",
  "                if not km.is_alive():\n",
  "                    send({\"id\": cid, \"type\": \"error\", \"ename\": \"Kernel died\", \"evalue\": \"\", \"traceback\": []})\n",
  "                    break\n",
  "                continue\n",
  "            if msg.get(\"parent_header\", {}).get(\"msg_id\") != msg_id:\n",
  "                continue\n",
  "            t, c = msg[\"msg_type\"], msg[\"content\"]\n",
  "            if t == \"stream\":\n",
  "                send({\"id\": cid, \"type\": \"stream\", \"name\": c[\"name\"], \"text\": c[\"text\"]})\n",
  "            elif t in (\"execute_result\", \"display_data\"):\n",
  "                count = c.get(\"execution_count\", count)\n",
  "                send({\"id\": cid, \"type\": \"result\" if t == \"execute_result\" else \"display\", \"count\": count,\n",
  "                      \"data\": c.get(\"data\", {})})\n",
  "            elif t == \"error\":\n",
  "                send({\"id\": cid, \"type\": \"error\", \"ename\": c[\"ename\"], \"evalue\": c[\"evalue\"],\n",
  "                      \"traceback\": c[\"traceback\"]})\n",
  "            elif t == \"execute_input\":\n",
  "                count = c.get(\"execution_count\", count)\n",
  "            elif t == \"status\" and c[\"execution_state\"] == \"idle\":\n",
  "                break\n",
  "        send({\"id\": cid, \"type\": \"done\", \"count\": count})\n",
  "    kc.stop_channels()\n",
  "    km.shutdown_kernel(now=True)\n",
  "\n",
  "\n",
  "# ---------------------------------------------------------------- plain Python\n",
  "class Stream(io.TextIOBase):\n",
  "    def __init__(self, cid, name):\n",
  "        self.cid, self.name = cid, name\n",
  "\n",
  "    def writable(self):\n",
  "        return True\n",
  "\n",
  "    def write(self, t):\n",
  "        if t:\n",
  "            send({\"id\": self.cid, \"type\": \"stream\", \"name\": self.name, \"text\": t})\n",
  "        return len(t)\n",
  "\n",
  "\n",
  "def figures(cid):\n",
  "    plt = sys.modules.get(\"matplotlib.pyplot\")\n",
  "    if plt is None:\n",
  "        return\n",
  "    for n in plt.get_fignums():\n",
  "        b = io.BytesIO()\n",
  "        plt.figure(n).savefig(b, format=\"png\", bbox_inches=\"tight\")\n",
  "        send({\"id\": cid, \"type\": \"display\",\n",
  "              \"data\": {\"image/png\": base64.b64encode(b.getvalue()).decode(\"ascii\"), \"text/plain\": \"<Figure>\"}})\n",
  "    plt.close(\"all\")\n",
  "\n",
  "\n",
  "def rich(v):\t# what an object shows: its PNG, its HTML (a pandas table), its repr\n",
  "    data = {\"text/plain\": repr(v)}\n",
  "    for attr, mime in ((\"_repr_png_\", \"image/png\"), (\"_repr_html_\", \"text/html\"), (\"_repr_markdown_\", \"text/markdown\")):\n",
  "        try:\n",
  "            f = getattr(v, attr, None)\n",
  "            if f is None:\n",
  "                continue\n",
  "            r = f()\n",
  "            if isinstance(r, tuple):\n",
  "                r = r[0]\n",
  "            if r is None:\n",
  "                continue\n",
  "            data[mime] = base64.b64encode(r).decode(\"ascii\") if isinstance(r, bytes) else str(r)\n",
  "        except Exception:\n",
  "            pass\n",
  "    return data\n",
  "\n",
  "\n",
  "def display(*objs, **kw):\t# IPython's display(), for the cells that call it\n",
  "    cid = CURRENT[0]\n",
  "    for o in objs:\n",
  "        send({\"id\": cid, \"type\": \"display\", \"data\": rich(o)})\n",
  "\n",
  "\n",
  "CURRENT = [0]\n",
  "NS = {\"__name__\": \"__main__\", \"display\": display}\n",
  "INPUTS = queue.Queue()\n",
  "BUSY = threading.Event()\n",
  "\n",
  "\n",
  "def ask(prompt=\"\"):\t# input(): mme asks the user, the answer comes back as op \"input\"\n",
  "    cid = CURRENT[0]\n",
  "    sys.stdout.flush()\n",
  "    send({\"id\": cid, \"type\": \"input\", \"prompt\": str(prompt), \"password\": False})\n",
  "    v = INPUTS.get()\n",
  "    if v is None:\n",
  "        raise KeyboardInterrupt\n",
  "    send({\"id\": cid, \"type\": \"stream\", \"name\": \"stdout\", \"text\": str(prompt) + v + \"\\n\"})\n",
  "    return v\n",
  "\n",
  "\n",
  "def completions(code, pos):\n",
  "    text = code[:pos]\n",
  "    m = re.search(r\"[A-Za-z_][A-Za-z0-9_.]*$|\\.$\", text)\n",
  "    word = m.group(0) if m else \"\"\n",
  "    start = pos - len(word)\n",
  "    try:\t# jedi, when it is there: what IPython uses\n",
  "        import jedi\n",
  "        line = text.count(\"\\n\") + 1\n",
  "        col = len(text) - (text.rfind(\"\\n\") + 1)\n",
  "        got = jedi.Interpreter(code, [NS]).complete(line, col)\n",
  "        name_start = pos - len(re.search(r\"[A-Za-z0-9_]*$\", text).group(0))\n",
  "        return [c.name for c in got][:200], name_start, pos\n",
  "    except Exception:\n",
  "        pass\n",
  "    import rlcompleter\n",
  "    c = rlcompleter.Completer(NS)\n",
  "    out, i = [], 0\n",
  "    while len(out) < 200:\n",
  "        r = c.complete(word, i)\n",
  "        if r is None:\n",
  "            break\n",
  "        if r not in out:\n",
  "            out.append(r.rstrip(\"(\"))\n",
  "        i += 1\n",
  "    return out, start, pos\n",
  "\n",
  "\n",
  "def run_plain():\n",
  "    try:\n",
  "        import matplotlib\n",
  "        matplotlib.use(\"Agg\")\t# figures are sent after each cell, as Jupyter's inline backend does\n",
  "    except Exception:\n",
  "        pass\n",
  "    import builtins, _thread, time\n",
  "    builtins.input = ask\n",
  "    NS[\"input\"] = ask\n",
  "    real_sleep = time.sleep\n",
  "\n",
  "    def sleep(s):\t# in short steps: an interrupt ends it at once (Windows' own sleep does not wake for it)\n",
  "        end = time.monotonic() + s\n",
  "        while True:\n",
  "            left = end - time.monotonic()\n",
  "            if left <= 0:\n",
  "                break\n",
  "            real_sleep(min(left, 0.05))\n",
  "\n",
  "    time.sleep = sleep\n",
  "    jobs = queue.Queue()\n",
  "\n",
  "    def reader():\t# the cells run on the main thread; this one reads mme meanwhile\n",
  "        for m in lines():\n",
  "            op = m.get(\"op\")\n",
  "            if op == \"exec\":\n",
  "                jobs.put(m)\n",
  "            elif op == \"interrupt\":\n",
  "                if BUSY.is_set():\n",
  "                    INPUTS.put(None)\t# a prompt waiting: it gives up\n",
  "                    _thread.interrupt_main()\t# KeyboardInterrupt in the cell, as Jupyter's\n",
  "            elif op == \"input\":\n",
  "                INPUTS.put(m.get(\"value\", \"\"))\n",
  "            elif op == \"complete\":\n",
  "                try:\n",
  "                    ms, s, e = completions(m[\"code\"], m[\"pos\"])\n",
  "                except Exception:\n",
  "                    ms, s, e = [], m[\"pos\"], m[\"pos\"]\n",
  "                send({\"type\": \"complete\", \"req\": m[\"req\"], \"matches\": ms, \"start\": s, \"end\": e})\n",
  "        jobs.put(None)\n",
  "        _thread.interrupt_main()\n",
  "\n",
  "    threading.Thread(target=reader, daemon=True).start()\n",
  "    send({\"type\": \"ready\", \"mode\": \"python\", \"info\": \"Python %s\" % sys.version.split()[0]})\n",
  "    count = 0\n",
  "    while True:\n",
  "        try:\n",
  "            m = jobs.get()\n",
  "        except KeyboardInterrupt:\t# an interrupt that came too late: nothing runs\n",
  "            continue\n",
  "        if m is None:\n",
  "            break\n",
  "        cid, code = m[\"id\"], m[\"code\"]\n",
  "        CURRENT[0] = cid\n",
  "        count += 1\n",
  "        name = \"Cell In[%d]\" % count\n",
  "        linecache.cache[name] = (len(code), None, code.splitlines(True), name)\n",
  "        so, se = sys.stdout, sys.stderr\n",
  "        sys.stdout, sys.stderr = Stream(cid, \"stdout\"), Stream(cid, \"stderr\")\n",
  "        while not INPUTS.empty():\n",
  "            INPUTS.get()\n",
  "        BUSY.set()\n",
  "        try:\n",
  "            try:\n",
  "                tree = ast.parse(code, name, \"exec\")\n",
  "                last = None\n",
  "                if tree.body and isinstance(tree.body[-1], ast.Expr):\n",
  "                    last = ast.Expression(tree.body.pop().value)\n",
  "                exec(compile(tree, name, \"exec\"), NS)\n",
  "                if last is not None:\n",
  "                    v = eval(compile(last, name, \"eval\"), NS)\n",
  "                    if v is not None:\n",
  "                        NS[\"_\"] = v\n",
  "                        send({\"id\": cid, \"type\": \"result\", \"count\": count, \"data\": rich(v)})\n",
  "                figures(cid)\n",
  "            except SystemExit:\n",
  "                pass\n",
  "            except BaseException:\n",
  "                et, ev, tb = sys.exc_info()\n",
  "                frames = [f for f in traceback.extract_tb(tb) if f.filename.startswith(\"Cell In[\")]\n",
  "                tr = []\n",
  "                if frames:\n",
  "                    tr.append(\"Traceback (most recent call last):\")\n",
  "                    tr += [l.rstrip(\"\\n\") for l in traceback.format_list(frames)]\n",
  "                tr += [l.rstrip(\"\\n\") for l in traceback.format_exception_only(et, ev)]\n",
  "                send({\"id\": cid, \"type\": \"error\", \"ename\": et.__name__, \"evalue\": str(ev), \"traceback\": tr})\n",
  "                try:\n",
  "                    figures(cid)\n",
  "                except Exception:\n",
  "                    pass\n",
  "            finally:\n",
  "                BUSY.clear()\n",
  "                sys.stdout, sys.stderr = so, se\n",
  "            send({\"id\": cid, \"type\": \"done\", \"count\": count})\n",
  "        except KeyboardInterrupt:\t# came just after the cell: it is done all the same\n",
  "            send({\"id\": cid, \"type\": \"done\", \"count\": count})\n",
  "\n",
  "\n",
  "if __name__ == \"__main__\":\n",
  "    kernel = sys.argv[1] if len(sys.argv) > 1 else \"python3\"\n",
  "    try:\n",
  "        import jupyter_client, ipykernel\t# noqa: F401  (a kernel needs both, for Python)\n",
  "        have = True\n",
  "    except ImportError:\n",
  "        have = False\n",
  "    if have and os.environ.get(\"MME_KERNEL\") != \"python\":\n",
  "        try:\n",
  "            run_jupyter(kernel)\n",
  "            sys.exit(0)\n",
  "        except Exception as e:\n",
  "            send({\"type\": \"log\", \"text\": \"Jupyter kernel %s could not start (%s): mme's Python runs the cells\" % (kernel, e)})\n",
  "    run_plain()\n",
